/*
	SDZArrayOfString.h
	The interface definition of properties and methods for the SDZArrayOfString array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@interface SDZArrayOfString : SoapArray
{
}

@end
