/*
	SDZAccessorial.h
	The interface definition of properties and methods for the SDZAccessorial object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface SDZAccessorial : SoapObject
{
	NSString* _accCode;
	
}
		
	@property (retain, nonatomic) NSString* accCode;

	+ (SDZAccessorial*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
