/*
	SDZArrayOfRateAdvisement.h
	The implementation of properties and methods for the SDZArrayOfRateAdvisement array.
	Generated by SudzC.com
*/
#import "SDZArrayOfRateAdvisement.h"

#import "SDZRateAdvisement.h"
@implementation SDZArrayOfRateAdvisement

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZRateAdvisement* value = [[SDZRateAdvisement createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"RateAdvisement"]];
		}
		return s;
	}
@end
