/*
	SDZArrayOfRateResponsePrivileged.h
	The implementation of properties and methods for the SDZArrayOfRateResponsePrivileged array.
	Generated by SudzC.com
*/
#import "SDZArrayOfRateResponsePrivileged.h"

#import "SDZRateResponsePrivileged.h"
@implementation SDZArrayOfRateResponsePrivileged

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZRateResponsePrivileged* value = [[SDZRateResponsePrivileged createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"RateResponsePrivileged"]];
		}
		return s;
	}
@end
