/*
	SDZArrayOfSupplement.h
	The interface definition of properties and methods for the SDZArrayOfSupplement array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZSupplement;
@interface SDZArrayOfSupplement : SoapArray
{
}

@end
