/*
	SDZArrayOfSupplement.h
	The implementation of properties and methods for the SDZArrayOfSupplement array.
	Generated by SudzC.com
*/
#import "SDZArrayOfSupplement.h"

#import "SDZSupplement.h"
@implementation SDZArrayOfSupplement

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZSupplement* value = [[SDZSupplement createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Supplement"]];
		}
		return s;
	}
@end
