/*
	SDZArrayOfPricingAccessorial.h
	The interface definition of properties and methods for the SDZArrayOfPricingAccessorial array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZPricingAccessorial;
@interface SDZArrayOfPricingAccessorial : SoapArray
{
}

@end
