/*
	SDZArrayOfFreight.h
	The implementation of properties and methods for the SDZArrayOfFreight array.
	Generated by SudzC.com
*/
#import "SDZArrayOfFreight.h"

#import "SDZFreight.h"
@implementation SDZArrayOfFreight

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZFreight* value = [[SDZFreight createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"Freight"]];
		}
		return s;
	}
@end
