/*
	SDZArrayOfRatedAccessorialPrivileged.h
	The interface definition of properties and methods for the SDZArrayOfRatedAccessorialPrivileged array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZRatedAccessorialPrivileged;
@interface SDZArrayOfRatedAccessorialPrivileged : SoapArray
{
}

@end
