/*
	SDZArrayOfArrayOfDecimal.h
	The implementation of properties and methods for the SDZArrayOfArrayOfDecimal array.
	Generated by SudzC.com
*/
#import "SDZArrayOfArrayOfDecimal.h"

#import "SDZArrayOfDecimal.h"
@implementation SDZArrayOfArrayOfDecimal

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				NSMutableArray* value = [[NSMutableArray createWithNode: child] object];
				[self addObject: value];
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [SDZArrayOfDecimal serialize: item]];
		}
		return s;
	}
@end
