/*
	SDZArrayOfAccessorial.h
	The interface definition of properties and methods for the SDZArrayOfAccessorial array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZAccessorial;
@interface SDZArrayOfAccessorial : SoapArray
{
}

@end
