/*
	SDZArrayOfArrayOfDecimal.h
	The interface definition of properties and methods for the SDZArrayOfArrayOfDecimal array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZArrayOfDecimal;
@interface SDZArrayOfArrayOfDecimal : SoapArray
{
}

@end
