/*
	SDZArrayOfStopOff.h
	The interface definition of properties and methods for the SDZArrayOfStopOff array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZStopOff;
@interface SDZArrayOfStopOff : SoapArray
{
}

@end
