/*
	SDZArrayOfRateResponsePrivileged.h
	The interface definition of properties and methods for the SDZArrayOfRateResponsePrivileged array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZRateResponsePrivileged;
@interface SDZArrayOfRateResponsePrivileged : SoapArray
{
}

@end
