/*
	SDZArrayOfAccessorialRateOverride.h
	The interface definition of properties and methods for the SDZArrayOfAccessorialRateOverride array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZAccessorialRateOverride;
@interface SDZArrayOfAccessorialRateOverride : SoapArray
{
}

@end
