/*
	SDZArrayOfRatedAccessorialPrivileged.h
	The implementation of properties and methods for the SDZArrayOfRatedAccessorialPrivileged array.
	Generated by SudzC.com
*/
#import "SDZArrayOfRatedAccessorialPrivileged.h"

#import "SDZRatedAccessorialPrivileged.h"
@implementation SDZArrayOfRatedAccessorialPrivileged

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZRatedAccessorialPrivileged* value = [[SDZRatedAccessorialPrivileged createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"RatedAccessorialPrivileged"]];
		}
		return s;
	}
@end
