/*
	SDZArrayOfTerminalInfo.h
	The implementation of properties and methods for the SDZArrayOfTerminalInfo array.
	Generated by SudzC.com
*/
#import "SDZArrayOfTerminalInfo.h"

#import "SDZTerminalInfo.h"
@implementation SDZArrayOfTerminalInfo

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZTerminalInfo* value = [[SDZTerminalInfo createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"TerminalInfo"]];
		}
		return s;
	}
@end
