/*
	SDZArrayOfTerminalInfo.h
	The interface definition of properties and methods for the SDZArrayOfTerminalInfo array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZTerminalInfo;
@interface SDZArrayOfTerminalInfo : SoapArray
{
}

@end
