/*
	SDZArrayOfFreightPricingDetails.h
	The interface definition of properties and methods for the SDZArrayOfFreightPricingDetails array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZFreightPricingDetails;
@interface SDZArrayOfFreightPricingDetails : SoapArray
{
}

@end
