/*
	SDZArrayOfDecimal.h
	The interface definition of properties and methods for the SDZArrayOfDecimal array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@interface SDZArrayOfDecimal : SoapArray
{
}

@end
