/*
	SDZArrayOfPalletPositions.h
	The implementation of properties and methods for the SDZArrayOfPalletPositions array.
	Generated by SudzC.com
*/
#import "SDZArrayOfPalletPositions.h"

#import "SDZPalletPositions.h"
@implementation SDZArrayOfPalletPositions

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZPalletPositions* value = [[SDZPalletPositions createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"PalletPositions"]];
		}
		return s;
	}
@end
