/*
	SDZArrayOfDecimal.h
	The implementation of properties and methods for the SDZArrayOfDecimal array.
	Generated by SudzC.com
*/
#import "SDZArrayOfDecimal.h"

@implementation SDZArrayOfDecimal

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				NSDecimalNumber* value = [NSDecimalNumber decimalNumberWithString: [child stringValue]];
				[self addObject: value];
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [NSString stringWithFormat: @"%@", item]];
		}
		return s;
	}
@end
