/*
	SDZArrayOfPalletPositions.h
	The interface definition of properties and methods for the SDZArrayOfPalletPositions array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZPalletPositions;
@interface SDZArrayOfPalletPositions : SoapArray
{
}

@end
