/*
	SDZArrayOfCwtPricingDetails.h
	The interface definition of properties and methods for the SDZArrayOfCwtPricingDetails array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZCwtPricingDetails;
@interface SDZArrayOfCwtPricingDetails : SoapArray
{
}

@end
