/*
	SDZArrayOfFreightPricingDetails.h
	The implementation of properties and methods for the SDZArrayOfFreightPricingDetails array.
	Generated by SudzC.com
*/
#import "SDZArrayOfFreightPricingDetails.h"

#import "SDZFreightPricingDetails.h"
@implementation SDZArrayOfFreightPricingDetails

	+ (id) createWithNode: (CXMLNode*) node
	{
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node
	{
		if(self = [self init]) {
			for(CXMLElement* child in [node children])
			{
				SDZFreightPricingDetails* value = [[SDZFreightPricingDetails createWithNode: child] object];
				if(value != nil) {
					[self addObject: value];
				}
			}
		}
		return self;
	}
	
	+ (NSMutableString*) serialize: (NSArray*) array
	{
		NSMutableString* s = [NSMutableString string];
		for(id item in array) {
			[s appendString: [item serialize: @"FreightPricingDetails"]];
		}
		return s;
	}
@end
