/*
	SDZArrayOfFreight.h
	The interface definition of properties and methods for the SDZArrayOfFreight array.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZFreight;
@interface SDZArrayOfFreight : SoapArray
{
}

@end
