/*
	SDZCarrierScacs.h
	The implementation of properties and methods for the SDZCarrierScacs object.
	Generated by SudzC.com
*/
#import "SDZCarrierScacs.h"

#import "SDZArrayOfString.h"
@implementation SDZCarrierScacs
	@synthesize scacs = _scacs;
	@synthesize contractId = _contractId;
	@synthesize strategyId = _strategyId;

	- (id) init
	{
		if(self = [super init])
		{
			self.scacs = [[[NSMutableArray alloc] init] autorelease];
			self.contractId = nil;
			self.strategyId = nil;

		}
		return self;
	}

	+ (SDZCarrierScacs*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.scacs = [[SDZArrayOfString createWithNode: [Soap getNode: node withName: @"scacs"]] object];
			self.contractId = [Soap getNodeValue: node withName: @"contractId"];
			self.strategyId = [Soap getNodeValue: node withName: @"strategyId"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"CarrierScacs"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.scacs != nil && self.scacs.count > 0) {
			[s appendFormat: @"<scacs>%@</scacs>", [SDZArrayOfString serialize: self.scacs]];
		} else {
			[s appendString: @"<scacs/>"];
		}
		if (self.contractId != nil) [s appendFormat: @"<contractId>%@</contractId>", [[self.contractId stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.strategyId != nil) [s appendFormat: @"<strategyId>%@</strategyId>", [[self.strategyId stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[SDZCarrierScacs class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		self.scacs = nil;
		self.contractId = nil;
		self.strategyId = nil;
		[super dealloc];
	}

@end
