/*
	SDZEffectivePricing.h
	The interface definition of properties and methods for the SDZEffectivePricing object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface SDZEffectivePricing : SoapObject
{
	BOOL _isMinimum;
	BOOL _isPercentPricing;
	NSDecimalNumber* _dollarOrPercentValue;
	
}
		
	@property BOOL isMinimum;
	@property BOOL isPercentPricing;
	@property (retain, nonatomic) NSDecimalNumber* dollarOrPercentValue;

	+ (SDZEffectivePricing*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
