/*
	SDZFreight.h
	The implementation of properties and methods for the SDZFreight object.
	Generated by SudzC.com
*/
#import "SDZFreight.h"

@implementation SDZFreight
	@synthesize description = _description;
	@synthesize length = _length;
	@synthesize width = _width;
	@synthesize height = _height;
	@synthesize freightClass = _freightClass;
	@synthesize weight = _weight;
	@synthesize volume = _volume;
	@synthesize units = _units;

	- (id) init
	{
		if(self = [super init])
		{
			self.description = nil;
			self.length = nil;
			self.width = nil;
			self.height = nil;
			self.freightClass = nil;
			self.weight = nil;
			self.volume = nil;

		}
		return self;
	}

	+ (SDZFreight*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.description = [Soap getNodeValue: node withName: @"description"];
			self.length = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"length"]];
			self.width = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"width"]];
			self.height = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"height"]];
			self.freightClass = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"freightClass"]];
			self.weight = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"weight"]];
			self.volume = [NSDecimalNumber decimalNumberWithString: [Soap getNodeValue: node withName: @"volume"]];
			self.units = [[Soap getNodeValue: node withName: @"units"] intValue];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"Freight"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.description != nil) [s appendFormat: @"<description>%@</description>", [[self.description stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];
		if (self.length != nil) [s appendFormat: @"<length>%@</length>", [NSString stringWithFormat: @"%@", self.length]];
		if (self.width != nil) [s appendFormat: @"<width>%@</width>", [NSString stringWithFormat: @"%@", self.width]];
		if (self.height != nil) [s appendFormat: @"<height>%@</height>", [NSString stringWithFormat: @"%@", self.height]];
		if (self.freightClass != nil) [s appendFormat: @"<freightClass>%@</freightClass>", [NSString stringWithFormat: @"%@", self.freightClass]];
		if (self.weight != nil) [s appendFormat: @"<weight>%@</weight>", [NSString stringWithFormat: @"%@", self.weight]];
		if (self.volume != nil) [s appendFormat: @"<volume>%@</volume>", [NSString stringWithFormat: @"%@", self.volume]];
		[s appendFormat: @"<units>%@</units>", [NSString stringWithFormat: @"%i", self.units]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[SDZFreight class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		self.description = nil;
		self.length = nil;
		self.width = nil;
		self.height = nil;
		self.freightClass = nil;
		self.weight = nil;
		self.volume = nil;
		[super dealloc];
	}

@end
