/*
	SDZPricingStrategyLevel.h
	The interface definition of properties and methods for the SDZPricingStrategyLevel object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
#import "SDZPricingBase.h"
@class SDZPricingBase;


@interface SDZPricingStrategyLevel : SDZPricingBase
{
	int _pricing_strategy_pk;
	int _strategy_id;
	
}
		
	@property int pricing_strategy_pk;
	@property int strategy_id;

	+ (SDZPricingStrategyLevel*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
