/*
	SDZPricingContractLevel.h
	The interface definition of properties and methods for the SDZPricingContractLevel object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
#import "SDZPricingBase.h"
@class SDZPricingBase;


@interface SDZPricingContractLevel : SDZPricingBase
{
	int _pricing_contract_pk;
	
}
		
	@property int pricing_contract_pk;

	+ (SDZPricingContractLevel*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
