/*
	SDZRateAdvisement.h
	The interface definition of properties and methods for the SDZRateAdvisement object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface SDZRateAdvisement : SoapObject
{
	NSString* _advisement;
	
}
		
	@property (retain, nonatomic) NSString* advisement;

	+ (SDZRateAdvisement*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
