/*
	SDZRateError.h
	The interface definition of properties and methods for the SDZRateError object.
	Generated by SudzC.com
*/

#import "Soap.h"
	

@interface SDZRateError : SoapObject
{
	int _errorId;
	NSString* _errorMessage;
	
}
		
	@property int errorId;
	@property (retain, nonatomic) NSString* errorMessage;

	+ (SDZRateError*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
