/*
	SDZRateServicePrivileged.h
	The interface definition of classes and methods for the RateServicePrivileged web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				
#import "SDZStopOff.h"
#import "SDZFreight.h"
#import "SDZPalletPositions.h"
#import "SDZAccessorial.h"
#import "SDZAccessorialRateOverride.h"
#import "SDZArrayOfString.h"
#import "SDZPricingAccessorial.h"
#import "SDZPricingContractLevel.h"
#import "SDZEffectivePricing.h"
#import "SDZPricingStrategyLevel.h"
#import "SDZArrayOfDecimal.h"
#import "SDZCwtPricingDetails.h"
#import "SDZFreightPricingDetails.h"
#import "SDZRatedAccessorialPrivileged.h"
#import "SDZSupplement.h"
#import "SDZTerminalInfo.h"
#import "SDZBilling3rdParty.h"
#import "SDZRateError.h"
#import "SDZRateAdvisement.h"
#import "SDZArrayOfStopOff.h"
#import "SDZArrayOfFreight.h"
#import "SDZArrayOfPalletPositions.h"
#import "SDZArrayOfAccessorial.h"
#import "SDZArrayOfAccessorialRateOverride.h"
#import "SDZCarrierScacs.h"
#import "SDZArrayOfRateResponsePrivileged.h"
#import "SDZArrayOfPricingAccessorial.h"
#import "SDZPricingBase.h"
#import "SDZPricingTransactionCharge.h"
#import "SDZPricingIncentive.h"
#import "SDZArrayOfArrayOfDecimal.h"
#import "SDZArrayOfCwtPricingDetails.h"
#import "SDZArrayOfFreightPricingDetails.h"
#import "SDZArrayOfRatedAccessorialPrivileged.h"
#import "SDZArrayOfSupplement.h"
#import "SDZArrayOfTerminalInfo.h"
#import "SDZArrayOfRateAdvisement.h"
#import "SDZDebugInfo.h"
#import "SDZRateResponsePrivileged.h"
#import "SDZRateReturn.h"
#import "SDZRateRequestPrivileged.h"

/* Interface for the service */
				
@interface SDZRateServicePrivileged : SoapService
		
	// Returns NSString*
	/*  */
	- (SoapRequest*) TestDBConnection: (id <SoapDelegate>) handler;
	- (SoapRequest*) TestDBConnection: (id) target action: (SEL) action;

	// Returns NSString*
	/*  */
	- (SoapRequest*) TestRateCall: (id <SoapDelegate>) handler;
	- (SoapRequest*) TestRateCall: (id) target action: (SEL) action;

	// Returns SDZRateReturn*
	/*  */
	- (SoapRequest*) RateShipment: (id <SoapDelegate>) handler rrp: (SDZRateRequestPrivileged*) rrp;
	- (SoapRequest*) RateShipment: (id) target action: (SEL) action rrp: (SDZRateRequestPrivileged*) rrp;

		
	+ (SDZRateServicePrivileged*) service;
	+ (SDZRateServicePrivileged*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	