/*
	SDZRateReturn.h
	The implementation of properties and methods for the SDZRateReturn object.
	Generated by SudzC.com
*/
#import "SDZRateReturn.h"

#import "SDZArrayOfRateResponsePrivileged.h"
#import "SDZRateError.h"
#import "SDZArrayOfRateAdvisement.h"
#import "SDZDebugInfo.h"
@implementation SDZRateReturn
	@synthesize rrp = _rrp;
	@synthesize re = _re;
	@synthesize rateTiming = _rateTiming;
	@synthesize ra = _ra;
	@synthesize di = _di;
	@synthesize resRateReturnHeaderGuid = _resRateReturnHeaderGuid;

	- (id) init
	{
		if(self = [super init])
		{
			self.rrp = [[[NSMutableArray alloc] init] autorelease];
			self.re = nil; // [[SDZRateError alloc] init];
			self.ra = [[[NSMutableArray alloc] init] autorelease];
			self.di = nil; // [[SDZDebugInfo alloc] init];
			self.resRateReturnHeaderGuid = nil;

		}
		return self;
	}

	+ (SDZRateReturn*) createWithNode: (CXMLNode*) node
	{
		if(node == nil) { return nil; }
		return [[[self alloc] initWithNode: node] autorelease];
	}

	- (id) initWithNode: (CXMLNode*) node {
		if(self = [super initWithNode: node])
		{
			self.rrp = [[SDZArrayOfRateResponsePrivileged createWithNode: [Soap getNode: node withName: @"rrp"]] object];
			self.re = [[SDZRateError createWithNode: [Soap getNode: node withName: @"re"]] object];
			self.rateTiming = [[Soap getNodeValue: node withName: @"rateTiming"] doubleValue];
			self.ra = [[SDZArrayOfRateAdvisement createWithNode: [Soap getNode: node withName: @"ra"]] object];
			self.di = [[SDZDebugInfo createWithNode: [Soap getNode: node withName: @"di"]] object];
			self.resRateReturnHeaderGuid = [Soap getNodeValue: node withName: @"resRateReturnHeaderGuid"];
		}
		return self;
	}

	- (NSMutableString*) serialize
	{
		return [self serialize: @"RateReturn"];
	}
  
	- (NSMutableString*) serialize: (NSString*) nodeName
	{
		NSMutableString* s = [NSMutableString string];
		[s appendFormat: @"<%@", nodeName];
		[s appendString: [self serializeAttributes]];
		[s appendString: @">"];
		[s appendString: [self serializeElements]];
		[s appendFormat: @"</%@>", nodeName];
		return s;
	}
	
	- (NSMutableString*) serializeElements
	{
		NSMutableString* s = [super serializeElements];
		if (self.rrp != nil && self.rrp.count > 0) {
			[s appendFormat: @"<rrp>%@</rrp>", [SDZArrayOfRateResponsePrivileged serialize: self.rrp]];
		} else {
			[s appendString: @"<rrp/>"];
		}
		if (self.re != nil) [s appendString: [self.re serialize: @"re"]];
		[s appendFormat: @"<rateTiming>%@</rateTiming>", [NSString stringWithFormat: @"%f", self.rateTiming]];
		if (self.ra != nil && self.ra.count > 0) {
			[s appendFormat: @"<ra>%@</ra>", [SDZArrayOfRateAdvisement serialize: self.ra]];
		} else {
			[s appendString: @"<ra/>"];
		}
		if (self.di != nil) [s appendString: [self.di serialize: @"di"]];
		if (self.resRateReturnHeaderGuid != nil) [s appendFormat: @"<resRateReturnHeaderGuid>%@</resRateReturnHeaderGuid>", [[self.resRateReturnHeaderGuid stringByReplacingOccurrencesOfString:@"\"" withString:@"&quot;"] stringByReplacingOccurrencesOfString:@"&" withString:@"&amp;"]];

		return s;
	}
	
	- (NSMutableString*) serializeAttributes
	{
		NSMutableString* s = [super serializeAttributes];

		return s;
	}
	
	-(BOOL)isEqual:(id)object{
		if(object != nil && [object isKindOfClass:[SDZRateReturn class]]) {
			return [[self serialize] isEqualToString:[object serialize]];
		}
		return NO;
	}
	
	-(NSUInteger)hash{
		return [Soap generateHash:self];

	}
	
	- (void) dealloc
	{
		self.rrp = nil;
		self.re = nil;
		self.ra = nil;
		self.di = nil;
		self.resRateReturnHeaderGuid = nil;
		[super dealloc];
	}

@end
