/*
	SDZRateServicePrivileged.m
	The implementation classes and methods for the RateServicePrivileged web service.
	Generated by SudzC.com
*/

#import "SDZRateServicePrivileged.h"
				
#import "Soap.h"
	
#import "SDZStopOff.h"
#import "SDZFreight.h"
#import "SDZPalletPositions.h"
#import "SDZAccessorial.h"
#import "SDZAccessorialRateOverride.h"
#import "SDZArrayOfString.h"
#import "SDZPricingAccessorial.h"
#import "SDZPricingContractLevel.h"
#import "SDZEffectivePricing.h"
#import "SDZPricingStrategyLevel.h"
#import "SDZArrayOfDecimal.h"
#import "SDZCwtPricingDetails.h"
#import "SDZFreightPricingDetails.h"
#import "SDZRatedAccessorialPrivileged.h"
#import "SDZSupplement.h"
#import "SDZTerminalInfo.h"
#import "SDZBilling3rdParty.h"
#import "SDZRateError.h"
#import "SDZRateAdvisement.h"
#import "SDZArrayOfStopOff.h"
#import "SDZArrayOfFreight.h"
#import "SDZArrayOfPalletPositions.h"
#import "SDZArrayOfAccessorial.h"
#import "SDZArrayOfAccessorialRateOverride.h"
#import "SDZCarrierScacs.h"
#import "SDZArrayOfRateResponsePrivileged.h"
#import "SDZArrayOfPricingAccessorial.h"
#import "SDZPricingBase.h"
#import "SDZPricingTransactionCharge.h"
#import "SDZPricingIncentive.h"
#import "SDZArrayOfArrayOfDecimal.h"
#import "SDZArrayOfCwtPricingDetails.h"
#import "SDZArrayOfFreightPricingDetails.h"
#import "SDZArrayOfRatedAccessorialPrivileged.h"
#import "SDZArrayOfSupplement.h"
#import "SDZArrayOfTerminalInfo.h"
#import "SDZArrayOfRateAdvisement.h"
#import "SDZDebugInfo.h"
#import "SDZRateResponsePrivileged.h"
#import "SDZRateReturn.h"
#import "SDZRateRequestPrivileged.h"

/* Implementation of the service */
				
@implementation SDZRateServicePrivileged

	- (id) init
	{
		if(self = [super init])
		{
			self.serviceUrl = @"http://139.146.200.58/WebServicesPrivileged/RateServicePrivileged.asmx";
			self.namespace = @"http://eshipmanager.com/";
			self.headers = nil;
			self.logging = NO;
		}
		return self;
	}
	
	- (id) initWithUsername: (NSString*) username andPassword: (NSString*) password {
		if(self = [super initWithUsername:username andPassword:password]) {
		}
		return self;
	}
	
	+ (SDZRateServicePrivileged*) service {
		return [SDZRateServicePrivileged serviceWithUsername:nil andPassword:nil];
	}
	
	+ (SDZRateServicePrivileged*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password {
		return [[[SDZRateServicePrivileged alloc] initWithUsername:username andPassword:password] autorelease];
	}

		
	// Returns NSString*
	/*  */
	- (SoapRequest*) TestDBConnection: (id <SoapDelegate>) handler
	{
		return [self TestDBConnection: handler action: nil];
	}

	- (SoapRequest*) TestDBConnection: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"TestDBConnection" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/TestDBConnection" postData: _envelope deserializeTo: @"NSString"];
		[_request send];
		return _request;
	}

	// Returns NSString*
	/*  */
	- (SoapRequest*) TestRateCall: (id <SoapDelegate>) handler
	{
		return [self TestRateCall: handler action: nil];
	}

	- (SoapRequest*) TestRateCall: (id) _target action: (SEL) _action
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		NSString* _envelope = [Soap createEnvelope: @"TestRateCall" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/TestRateCall" postData: _envelope deserializeTo: @"NSString"];
		[_request send];
		return _request;
	}

	// Returns SDZRateReturn*
	/*  */
	- (SoapRequest*) RateShipment: (id <SoapDelegate>) handler rrp: (SDZRateRequestPrivileged*) rrp
	{
		return [self RateShipment: handler action: nil rrp: rrp];
	}

	- (SoapRequest*) RateShipment: (id) _target action: (SEL) _action rrp: (SDZRateRequestPrivileged*) rrp
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		[_params addObject: [[[SoapParameter alloc] initWithValue: rrp forName: @"rrp"] autorelease]];
		NSString* _envelope = [Soap createEnvelope: @"RateShipment" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://eshipmanager.com/RateShipment" postData: _envelope deserializeTo: [[SDZRateReturn alloc] autorelease]];
		[_request send];
		return _request;
	}


@end
	