/*
	SDZRateReturn.h
	The interface definition of properties and methods for the SDZRateReturn object.
	Generated by SudzC.com
*/

#import "Soap.h"
	
@class SDZArrayOfRateResponsePrivileged;
@class SDZRateError;
@class SDZArrayOfRateAdvisement;
@class SDZDebugInfo;

@interface SDZRateReturn : SoapObject
{
	NSMutableArray* _rrp;
	SDZRateError* _re;
	double _rateTiming;
	NSMutableArray* _ra;
	SDZDebugInfo* _di;
	NSString* _resRateReturnHeaderGuid;
	
}
		
	@property (retain, nonatomic) NSMutableArray* rrp;
	@property (retain, nonatomic) SDZRateError* re;
	@property double rateTiming;
	@property (retain, nonatomic) NSMutableArray* ra;
	@property (retain, nonatomic) SDZDebugInfo* di;
	@property (retain, nonatomic) NSString* resRateReturnHeaderGuid;

	+ (SDZRateReturn*) createWithNode: (CXMLNode*) node;
	- (id) initWithNode: (CXMLNode*) node;
	- (NSMutableString*) serialize;
	- (NSMutableString*) serialize: (NSString*) nodeName;
	- (NSMutableString*) serializeAttributes;
	- (NSMutableString*) serializeElements;

@end
