/*
	SDZSudzc.m
	Creates a list of the services available with the SDZ prefix.
	Generated by SudzC.com
*/
#import "SDZSudzc.h"

@implementation SDZSudzC

@synthesize logging, server, defaultServer;

@synthesize rateServicePrivileged;


#pragma mark Initialization

-(id)initWithServer:(NSString*)serverName{
	if(self = [self init]) {
		self.server = serverName;
	}
	return self;
}

+(SDZSudzC*)sudzc{
	return (SDZSudzC*)[[[SDZSudzC alloc] init] autorelease];
}

+(SDZSudzC*)sudzcWithServer:(NSString*)serverName{
	return (SDZSudzC*)[[[SDZSudzC alloc] initWithServer:serverName] autorelease];
}

#pragma mark Methods

-(void)setLogging:(BOOL)value{
	logging = value;
	[self updateServices];
}

-(void)setServer:(NSString*)value{
	[server release];
	server = [value retain];
	[self updateServices];
}

-(void)updateServices{

	[self updateService: self.rateServicePrivileged];
}

-(void)updateService:(SoapService*)service{
	service.logging = self.logging;
	if(self.server == nil || self.server.length < 1) { return; }
	service.serviceUrl = [service.serviceUrl stringByReplacingOccurrencesOfString:defaultServer withString:self.server];
}

#pragma mark Getter Overrides


-(SDZRateServicePrivileged*)rateServicePrivileged{
	if(rateServicePrivileged == nil) {
		rateServicePrivileged = [[SDZRateServicePrivileged alloc] init];
	}
	return rateServicePrivileged;
}


@end
			